### ISSUE TITLE
ejsexcel 是不是有本地编译要求，在win下老有问题。

### ISSUE THREAD

**Issue by mrlong** [sail-sail/ejsExcel#16]
npm info prepublish ppms@0.0.1
ejsexcel@3.4.9 node_modules\ejsexcel
npm info ok

mrlong@mrlong-win10 MINGW64 /c/code/ppms/src
$ node ppmsapp.js

C:\code\ppms\src\node_modules\ejsexcel\ejsExcel.js:190
  sheetSufStr = Buffer.from("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone
=\"yes\"?>\n<%\nvar _data_ = _args._data_;\nvar _charPlus_ = _args._charPlus_;\n
var _charToNum_ = _args._charToNum_;\nvar _str2Xml_ = _args._str2Xml_;\nvar _hid
eSheet_ = _args._hideSheet_;\nvar _showSheet_ = _args._showSheet_;\nvar _deleteS
heet_ = _args._deleteSheet_;\nvar _ps_ = _args._ps_;\nvar _pi_ = _args._pi_;\nva
r _pf_ = _args._pf_;\nvar _acVar_ = _args._acVar_;\nvar _r = 0;\nvar _c = 0;\nva
r _row = 0;\nvar _col = \"\";\nvar _rc = \"\";\nvar _img_ = _args._img_;\nvar _q
rcode_ = _args._qrcode_;\nvar _mergeCellArr_ = [];\nvar _mergeCellFn_ = function
(mclStr) {\n    _mergeCellArr_.push(mclStr);\n};\nvar _hyperlinkArr_ = [];\nvar
_outlineLevel_ = _args._outlineLevel_;\n%>");
                       ^
TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (C:\code\ppms\src\node_modules\ejsexcel\ejsExcel.js:19
0:24)
    at Object.<anonymous> (C:\code\ppms\src\node_modules\ejsexcel\ejsExcel.js:15
23:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\code\ppms\src\controllers\budget\project\project-i
ndex.js:12:16)

**Comment by mrlong** [comment]
node.js 是6.x 的版本.

**Comment by mrlong** [comment]
@sail-sail 我的版本是6.x

**Comment by sail-sail** [comment]
没有win版本问题的, 底层是纯js写的, 我这里跟Q群里的人都是没有问题的, 加我Q,  151263555 让我看看,

**Comment by mrlong** [comment]
@sail-sail  谢谢了，我原来的4.x 版本，更级到6.x 之后好了.

**Comment by sail-sail** [comment]
@mrlong 我还是重复以前说的话:  package.json 里也有说, nodejs的版本必须大于等于 4.5.0
