### ISSUE TITLE
很奇怪，用绝对路径就报错，相对路径可以。

### ISSUE THREAD

**Issue by jay763190097** [sail-sail/ejsExcel#19]
```
//'F:\\node-project\\infostation\\dist\\config\\export\\separation.xlsx'
fs.readFile("./separation.xlsx", function (err, exlBuf) {
    if(err){
            console.log('read excel template error:',err);
    } else {
        console.log(exlBuf);
        ejsExcel.renderExcel(exlBuf, data).then(function(exlBuf2) {
        	fs.writeFileSync("./separation2.xlsx", exlBuf2);
        	console.log("生成separation.xlsx");
        }).catch(function(err) {
        	console.error(err);
        });
    }
});
```
用第一个路径，报错
```
[2017-10-17 15:45:13.903] [ERROR] mongodb - renderExcel error: { ReferenceError: _data is not defined
    at Object.anonymous (eval at <anonymous> (F:\node-project\infostation\dist\resources\node_modules\ejsExcel\ejsExcel.js:1133:26), <anonymous>:24:9874)
    at next (native)
    at onFulfilled (F:\node-project\infostation\dist\resources\node_modules\ejsExcel\lib\co\index.js:71:17)
    at co (F:\node-project\infostation\dist\resources\node_modules\ejsExcel\lib\co\index.js:56:10)
    at Object.<anonymous> (F:\node-project\infostation\dist\resources\node_modules\ejsExcel\ejsExcel.js:74:14)
    at Object.<anonymous> (F:\node-project\infostation\dist\resources\node_modules\ejsExcel\ejsExcel.js:1134:35)
    at next (native)
    at step (F:\node-project\infostation\dist\resources\node_modules\ejsExcel\ejsExcel.js:1:270)
    at F:\node-project\infostation\dist\resources\node_modules\ejsExcel\ejsExcel.js:1:447
    at process._tickDomainCallback (internal/process/next_tick.js:129:7) is_out: true }
```

**Comment by sail-sail** [comment]
_data 不存在, 改为 _data_ 即可
