### ISSUE TITLE
ValidationError: "startElement" is not allowed

### ISSUE THREAD

**Issue by xiaoyunchen** [sail-sail/ejsExcel#5]
第一次使用，出现如下报错
包已经是最新版本，使用的脚本和excel也都是官方提供的test文件。

`{ ValidationError: "startElement" is not allowed. "endElement" is not allowed. "sanitizeFn" is not allowed
    at Object.exports.process (/Users/xiaoyun/gitlab/e2e-demo/node_modules/joi/lib/errors.js:154:19)
    at _validateWithOptions (/Users/xiaoyun/gitlab/e2e-demo/node_modules/joi/lib/any.js:601:31)
    at root.validate (/Users/xiaoyun/gitlab/e2e-demo/node_modules/joi/lib/index.js:105:23)
    at Object.module.exports [as toJson] (/Users/xiaoyun/gitlab/e2e-demo/node_modules/xml2json/lib/xml2json.js:152:26)
    at /Users/xiaoyun/gitlab/e2e-demo/node_modules/ejsexcel/ejsExcel.js:757:29
    at next (native)
    at step (/Users/xiaoyun/gitlab/e2e-demo/node_modules/ejsexcel/ejsExcel.js:1:253)
    at /Users/xiaoyun/gitlab/e2e-demo/node_modules/ejsexcel/ejsExcel.js:1:430
    at process._tickCallback (internal/process/next_tick.js:103:7)
`

**Comment by sail-sail** [comment]
我本地多次测试过,是没问题的,  很多人也在用也是没问题的
at Object.exports.process (/Users/xiaoyun/gitlab/e2e-demo/node_modules/joi/lib/errors.js:154:19)
at _validateWithOptions (/Users/xiaoyun/gitlab/e2e-demo/node_modules/joi/lib/any.js:601:31)
at root.validate (/Users/xiaoyun/gitlab/e2e-demo/node_modules/joi/lib/index.js:105:23)
通过你的错误信息,可以看出,报错的位置是在一个你自己的第3方模块叫 joi 模块里面,对我的一些方法做出了限制
我看看这个joi模块有什么蹊跷

**Comment by sail-sail** [comment]
joi模块
Object schema description language and validator for JavaScript objects.
对对象的某些熟悉进行验证,限制, 具体哪些属性名要限制, 由自己编写
startElement endElemen sanitizeFn
这三个属性被 joi 限制了, 不允许出现在我的对象上

**Comment by xiaoyunchen** [comment]
所以是我使用joi 版本的问题？

**Comment by sail-sail** [comment]
应该不是, 没猜错的话应该是你的joi使用中,前面某个地方对类似这三个属性startElement endElemen sanitizeFn 做出了限制
不然你试试 ejsexcel/test/test.bat 双击, 本身的例子就是没问题的

**Comment by xiaoyunchen** [comment]
sorry  我用的MAC，没法运行bat
我单独运行 ` node ./test/testExcel.js ` 也是会报错

**Comment by sail-sail** [comment]
mac电脑的nodejs 6.x版本没有编译 npm install node-expat@2.0.0
导致的问题
