### ISSUE TITLE
数据对象属性名是数字时，导出报错 SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by codezyx** [sail-sail/ejsExcel#73]
这个问题找了两个小时，最终确定是excel模板里面配置了 <%forRow eny in _data_%><%=eny.123%> ，原因就是因为这个 eny.123，把123换成其他字母开头的属性名没有问题，我特意测试了一下，只要是数字开头就会报错，错误示例：123，2abc，只要不是数字开头就没问题。我只测试了字母开头的是没问题的。
SyntaxError: missing ) after argument list
    at Object.<anonymous> (D:\webProjects\test\node_modules\_ejsexcel@3.6.2@ejsexcel\ejsExcel.js:1157:26)
    at Generator.next (<anonymous>)
    at step (D:\webProjects\test\node_modules\_ejsexcel@3.6.2@ejsexcel\ejsExcel.js:1:191)
    at D:\webProjects\test\node_modules\_ejsexcel@3.6.2@ejsexcel\ejsExcel.js:1:368
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by sail-sail** [comment]
原因很简单, 因为ejsExcel底层的原理就是执行javascript本身, 所以, 所有javascript语法都支持, 几乎所有不是javascript语法都不支持, 除了那几个特殊的,  eny.123 是javascript语法不允许的

**Comment by codezyx** [comment]
我实在没办法了把数字属性名都加了一个字母前缀来规避这个问题，写前端还是得专业前端啊，我这看源码都看不懂。

**Comment by sail-sail** [comment]
那你为啥不用标准的javascript语法, 这样 eny['123'] 呢?

**Comment by codezyx** [comment]
> 那你为啥不用标准的javascript语法, 这样 eny['123'] 呢?

还真的可以啊，这个方式太好了
